### ISSUE TITLE
Add recon_all reportlet

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/niworkflows#102]
Inspired by https://surfer.nmr.mgh.harvard.edu/fswiki/QATools, but simpler (without the skullstrippping or 3D plots). Limited to outlines of pial and white matter surfaces. Similar to the segmentation plot, but with thinner lines and potentailly more slices.

**Comment by effigies** [comment]
Just to clarify: You want white/pial surfaces overlaid on the anatomical?

**Comment by chrisfilo** [comment]
Could you confirm first that those are indeed the surfaces that bbregister is using? (either through the mailing list or tracing which files does the binary open)

**Comment by effigies** [comment]
It uses the [white matter surface and cortical thickness measures](https://www.mail-archive.com/freesurfer@nmr.mgh.harvard.edu/msg25474.html), but not the [pial surface](https://mail.nmr.mgh.harvard.edu/pipermail//freesurfer/2017-January/049464.html). Does this affect your thinking on what boundaries to show?

Assuming we do want to show white/pial surfaces, [`$SUBJECTS_DIR/$SUBJ/mri/ribbon.mgz`](http://freesurfer.net/fswiki/ReconAllDevTable#line-127) is a volume file [generated](https://surfer.nmr.mgh.harvard.edu/fswiki/mris%25volmask) from the white and pial surfaces, so it could probably be used directly (or with minor modifications) from the existing segmentation report code. Does that sound reasonable, or do we need to overlay the surfaces themselves (doesn't seem to be an existing nilearn function)?

**Comment by oesteban** [comment]
Wow, that totally changes my understanding of how bbregister works. Great job figuring this out, @effigies !

I think we don't want to dive into the complications of rendering the intersection of the meshes with the imaging planes... so the ```ribbon.mgz``` solution with nilearn sounds good to me. WDYT @chrisfilo ?

**Comment by chrisfilo** [comment]
Yup that sounds very reasonable.

Since the two outlines (inner and outer) of the ribbon will be very close
to each other consider reducing the thickness of the lines you use.
