### ISSUE TITLE
Fix automated downloads after install

### ISSUE THREAD

**Issue by oesteban** [poldracklab/niworkflows#12]
Similarily to #1, since we started to download all the templates after a fresh install I'm getting this:

```
error: niworkflows tried to store the dataset in the following directories, but:
 -/scratch/users/crn_plab/.cache/stanford-crn/brainweb (SandboxViolation: mkdir(u'/scratch/users/crn_plab/.cache/stanford-crn/brainweb', 511) {}

The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.

This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand.  Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.)
```
cc @rwblair

**Comment by oesteban** [comment]
A related issue:
```
 File "/usr/local/miniconda/bin/mriqc", line 11, in <module>
    load_entry_point('mriqc', 'console_scripts', 'mriqc')()
  File "/root/src/mriqc/mriqc/utils/mriqc_run.py", line 211, in main
    run_id=opts.run_id, settings=settings)
  File "/root/src/mriqc/mriqc/workflows/core.py", line 46, in ms_anat
    anat_qc = anat_qc_workflow(settings=settings)
  File "/root/src/mriqc/mriqc/workflows/anatomical.py", line 72, in anat_qc_workflow
    amw = airmsk_wf()
  File "/root/src/mriqc/mriqc/workflows/anatomical.py", line 396, in airmsk_wf
    invt.inputs.input_image = op.join(get_mni_icbm152_nlin_asym_09c(), '1mm_headmask.nii.gz')
  File "/usr/local/miniconda/lib/python2.7/site-packages/niworkflows/data/getters.py", line 141, in get_mni_icbm152_nlin_asym_09c
    return get_dataset('mni_icbm152_nlin_asym_09c', data_dir, url, resume, verbose)
  File "/usr/local/miniconda/lib/python2.7/site-packages/niworkflows/data/getters.py", line 49, in get_dataset
    md5sum=md5):
  File "/usr/local/miniconda/lib/python2.7/site-packages/niworkflows/data/utils.py", line 168, in _fetch_file
    shutil.move(temp_part_name, temp_full_name)
  File "/usr/local/miniconda/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/local/miniconda/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/local/miniconda/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: u'/scratch/users/crn_plab/.cache/stanford-crn/downloads/580705089ad5a101f17944a9.part'
```

When submitting several parallel processes without the cache initialized, they will try to download the data first.

We should:
  1. Define a system-wide cache, where we download the templates at installation. And effectively solving the EasyInstall problem.
  2. Do not crash if the installer is not able to download the templates, just issue a warning.

**Comment by oesteban** [comment]
@chrisfilo - I think this problem is worse with singularity containers. Even though the new Dockerfile of mriqc has a RUN command to pre-cache the templates, since they are stored in /root/.cache I think they are not accessible inside the container.

**Comment by oesteban** [comment]
@chrisfilo - adding the template as package_data does not work: the template is 155MB and the maximum pypi project size (by default) is 60MB or so.

**Comment by vsoch** [comment]
Why not just set cache to be an environmental variable? Then it could be defined outside the container, and the container could mount when needed.

**Comment by chrisfilo** [comment]
That could work. The env variable could be defined inside the container and
read by the download script.

**Comment by oesteban** [comment]
Like this: https://github.com/poldracklab/niworkflows/blob/master/niworkflows/data/utils.py#L40

**Comment by chrisfilo** [comment]
Yes but pointing to an absolute path like /use/share/data instead of the
home directory

On Nov 11, 2016 3:18 PM, "Oscar Esteban" <notifications@github.com> wrote:

Like this: https://github.com/poldracklab/niworkflows/blob/
master/niworkflows/data/utils.py#L40

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/poldracklab/niworkflows/issues/12#issuecomment-260078041>,
or mute the thread

**Comment by oesteban** [comment]
The 09c template now belongs in this package distribution. That should ease this problem.

**Comment by oesteban** [comment]
This was solved, even though the package is almost at the 55MB limit. Close for now.
