### ISSUE TITLE
0.0.6 didn't upload to PyPI

### ISSUE THREAD

**Issue by effigies** [poldracklab/niworkflows#139]
https://pypi.python.org/pypi/niworkflows

**Comment by oesteban** [comment]
Yep, I'm trying to fix this just by using `twine`. After googling the error, I did not find out much useful information. I removed and recreated the tag: https://circleci.com/gh/poldracklab/niworkflows/214

**Comment by oesteban** [comment]
Also, I added that lame copy in the end, so if we keep finding problems, at least the distribution file will be available as an artifact to manually submit to pypi, just in case.

**Comment by chrisfilo** [comment]
FYI CircleCI never successfully built the 0.0.6 tag: https://circleci.com/gh/poldracklab/niworkflows That's why it was never pushed to PyPi (sorry if I'm stating the obvious).

**Comment by effigies** [comment]
Eh. Whole issue was stating the obvious. (Didn't check latest commits.)
