### ISSUE TITLE
Independent bash script for downloads

### ISSUE THREAD

**Issue by oesteban** [poldracklab/niworkflows#147]
It'd be helpful a bash script that downloads and stores the data associated to niworkflows without python (based on curl). I am thinking particularly of the long time it takes for fmriprep's docker-build to download them.

Additionally, by setting this script at the top of the Dockerfile we'd skip this layer (would be cached) in all builds. Right now, the layer depends on others that are never cached. A bummer when OSF is down (like yesterday night) that would be less problematic if layers are properly cached.

**Comment by effigies** [comment]
Have a working script, for fmriprep specifically, here: https://github.com/poldracklab/fmriprep/commit/0396f359f74bb9f7e366313521dbd3f76b9eabe2

**Comment by oesteban** [comment]
Addressed in https://github.com/poldracklab/fmriprep/pull/738
