### ISSUE TITLE
[TESTING] Use nipype to run tests in parallel

### ISSUE THREAD

**Issue by effigies** [poldracklab/niworkflows#201]
Currently we're creating nodes and testing them serially, which seems silly given that this library is for entries in a pipelining utility. I'd suggest the following architecture:

- Test series 1: Create nodes and add to workflow (using reasonable estimates of memory and threads)
- Test 2: Run workflow in parallel
- Test series 3: Check outputs

Doing it this way, we could probably get the total runtime down to antsBrainExtraction + overhead. Might even be able to go back to a single container, given each container gets 32 cores.

**Comment by oesteban** [comment]
When I started playing around parallel execution on the nipype repo, I found out that >2 parallel threads the performance drops. Those 32 cores /proc/cpu reports must be virtual, I guess. Just to note it down bc I think it is relevant: those 32 cores will not return what you expect...

**Comment by oesteban** [comment]
I'd say #225 addressed this. I'll let you close this PR if so.
