### ISSUE TITLE
Problems with BETRPT

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/niworkflows#24]
A few things:

- [x] when `generate_report==True` force `mask` input to True
- [x] always use the mask_file output (not any output that has ".nii" in its name)
- [x] remove the warning https://github.com/poldracklab/niworkflows/blob/master/niworkflows/common/report_interfaces.py#L69

Those changes should greatly simplify `_overlay_file_name()` and `_pick_output_file()` ideally making one of them redundant. There also shouldn't be  any need for the try/catch in https://github.com/poldracklab/niworkflows/blob/master/niworkflows/common/report_interfaces.py#L101 (it unclear what weird inputs are you referring to) as well as the conditional in https://github.com/poldracklab/niworkflows/blob/master/niworkflows/common/report_interfaces.py#L117

Those issue could be addressed in separate PR or in https://github.com/poldracklab/niworkflows/pull/23

**Comment by oesteban** [comment]
All of this is addressed in #22.

I am setting the input mask to True, but we could go away without it by masking the output (only brain) file: https://github.com/oesteban/niworkflows/blob/28d306fa2ca67fc437c062874d019853fb49ac2b/niworkflows/viz/utils.py#L86

**Comment by shoshber** [comment]
Have you merged in my recent changes?
