### ISSUE TITLE
Suboptimal scaling of some confounds in reports

### ISSUE THREAD

**Issue by oesteban** [poldracklab/niworkflows#242]
[from poldracklab/fmriprep#1143]

![image](https://user-images.githubusercontent.com/238759/40269233-e4cd8862-5b40-11e8-8ba4-9c5a79a2913b.png)

It's hard to see variation in WM and CSF with this scaling.

**Comment by effigies** [comment]
Been thinking about this a little. Let's use -1 to 1 to describe the vertical axis, and for the time series `X`, let `a = min`, `b = max`, `m = mean`.

So `(X - m) / m` will be centered at the mean and scaled by the mean. In this scale, a change of 10% of the mean will appear as +/-0.1, or a 20th of the [-1, 1] range. If we want that to be a quarter of the plot range, then multiply by 5, so the effective time series is `5 (X - m) / m`.

Thus I think a viable scaling option takes the form `(X - m) / max(m / P, m - a, b - m)`, where `P` is an inflation factor from % change of mean to % distance to y-axis bounds. `m - a` and `b - m` ensure that the max and min do not go off the plot.

(I'll note that we definitely do not want to scale by variance, as that would make comparing variance between BOLD series impossible.)

**Comment by wiheto** [comment]
So I think this can be solved by multiplying the range of values with a scalar instead of the min/max

Something like: 

```
nonnan_range = (nonnan.max() - nonnan.min())
def_ylims = [nonnan.min() - 0.1 * nonnan_range, 1.1 * nonnan_range]
```

Maybe the scalar still needs to be tuned, but this should stop the squashing phenomena, I think.

**Comment by wiheto** [comment]
Did some testing, this scaling works quite well with varying y-axis ranges. 

Anyone objects? Can submit PR otherwise.

**Comment by oesteban** [comment]
No objections at all, please send that PR :)

**Comment by oesteban** [comment]
Fixed in https://github.com/poldracklab/niworkflows/commit/a71c8346da5e100cb596e4f91a54a1f769d78dfc
