### ISSUE TITLE
Fatal Python error: Bus error

### ISSUE THREAD

**Issue by oesteban** [poldracklab/niworkflows#246]
As reported by @marcelzwiers in poldracklab/mriqc#717 and diagnosed by @effigies (https://github.com/poldracklab/mriqc/issues/717#issuecomment-395526216), there is a problem in `niworkflows/interfaces/utils.py`, line 179 (`_copyxform`) when using nibabel with mmap.

**Comment by effigies** [comment]
I looked at that stack trace a little more... It's not clear that it's an `mmap` issue, as these are `.nii.gz` files, which won't get `mmap`ed.

**Comment by effigies** [comment]
At least, I don't think so. You could always set `mmap=False` in `nb.load`, just to be safe.

**Comment by marcelzwiers** [comment]
If there is an intermediate solution that I can try or a test that I can perform, please let me know

**Comment by effigies** [comment]
Thanks for the offer. It looks like you're running locally, as opposed to in a Docker or Singularity container, so it should be relatively simple to set up a development environment. I'd start by cloning niworkflows and installing it in "editable" mode:

```Shell
git clone https://github.com/poldracklab/niworkflows.git
cd niworkflows
pip install -e .
```

Then any changes you make in the `niworkflows` directory will be immediately accessible.

The change I've proposed making is in [niworkflows/interfaces/utils.py#L160](https://github.com/poldracklab/niworkflows/blob/b2ae338b860d671b754088eefa477b7fb706c14a/niworkflows/interfaces/utils.py#L160):

```Diff
-    resampled = nb.load(out_image)
+    resampled = nb.load(out_image, mmap=False)
```

**Comment by marcelzwiers** [comment]
Thanks @effigies, setting mmap=false solved the problem! Apart from a few warnings (failed uploads, divide by zero and complex results) everything ran smoothly and produced nice looking reports :-)

**Comment by effigies** [comment]
Great! We can make this change when I get back to a computer. Expect it in the next release.
