### ISSUE TITLE
Factor out OSF getter into small package

### ISSUE THREAD

**Issue by effigies** [poldracklab/niworkflows#250]
The OSF dataset getters are a pretty useful piece of code that would be worth factoring into a small package that we import here. This would make transitioning to niflows simpler, and may be useful for other scientific packages.

I would picture this package mostly consisting of the equivalent of `get_dataset()`:

https://github.com/poldracklab/niworkflows/blob/b57a21974a05fb7148ba310701c847fc83a63122/niworkflows/data/getters.py#L52-L76

And then we provide a standard way to register a batch of names with file IDs and hashes.

**Comment by oesteban** [comment]
With the migration to datalad we barely use getters. Should we also migrate the test data and remove the getters module for good?

**Comment by effigies** [comment]
Let's deprecate it and leave it in for a couple minor versions. There's no rush to remove stuff. Nibabel has some deprecation machinery that will raise errors if the version passes the planned removal version.
