### ISSUE TITLE
Wrong time unit in confounds graph

### ISSUE THREAD

**Issue by shirareznik** [poldracklab/niworkflows#260]
Hi,
The unit in the counfounds graph should be "volumes" (or similar), not seconds...

![seconds_vols](https://user-images.githubusercontent.com/1251466/48579361-ee3efd00-e924-11e8-8e10-c66afb9d4c81.png)

Many thanks

**Comment by wiheto** [comment]
#261 is submitted and fixes the bug. It will be merged at some point.
