### ISSUE TITLE
Remove ``SignalExtraction`` ?

### ISSUE THREAD

**Issue by oesteban** [poldracklab/niworkflows#265]
It seems like we do not use the SignalExtraction from fmriprep anymore (recently moved into niworkflows codebase). Can we just delete this one?

**Comment by effigies** [comment]
Actually, it looks like we never used the implementation in poldracklab/fmriprep#1170, even though it was faster and took less memory. Maybe we should switch to using it?

**Comment by oesteban** [comment]
Hell yeah then

**Comment by effigies** [comment]
Do you have an fmriprep branch open to test moving all of these components to niworkflows? We can just update there.

**Comment by oesteban** [comment]
:+1:
