### ISSUE TITLE
`niworkflows.utils.bids.collect_data` failing to retrieve BOLD images

### ISSUE THREAD

**Issue by oesteban** [poldracklab/niworkflows#293]
It seems that the original bug causing poldracklab/fmriprep#1481 is still there (https://neurostars.org/t/fmriprep-from-singularity-unboundlocalerror/3299/9?u=oesteban).

Not getting a `'bold'` entry after the BIDSLayout query would explain the original UnboundLocalError symptom. @emdupre first noticed this during #285.

@effigies, any quick thoughts about what could've changed in pybids land that we did not account for in our end?

**Comment by effigies** [comment]
We're still depending on pybids 0.6.5... Nothing has changed in that. Unless there's some reason that 0.7.0 is getting pulled in?

**Comment by oesteban** [comment]
@emdupre could not replicate the original bug, and the error seems persistent only with singularity containers. Maybe a system-wide installation pybids installation is coming into play.

**Comment by oesteban** [comment]
Seems like the original UnboundLocalError is not happening anymore. Please reopen in case of regression.
