### ISSUE TITLE
ReportCapableInterface should overload run(), not _run_interface()

### ISSUE THREAD

**Issue by shoshber** [poldracklab/niworkflows#30]

**Comment by chrisfilo** [comment]
Could you elaborate on the justification?

**Comment by shoshber** [comment]
If we overload `run()`, merging `ReportCapableInterface` with `BaseInterface`is a simple matter of copying the `ReportCapableInterface.run()` code into `BaseInterface.run()` (which is too big, but that's another concern). For now, overloading `_run_interface()` works perfectly well (aside from some complicated error handling and passing), but when we merge the interfaces, it will entail a lot of changes because `BaseInterface._run_interface()` is abstract by design (raises `NotImplementedException`).

I originally wrote `ReportCapableInterface` as overloading `run()`, but that doesn't work for some reason, so Ross switched to `_run_interface()` for now. It is puzzling, because according to the architecture of nipype it ~should~ work.

**Comment by chrisfilo** [comment]
I don't think it makes sense to merge this functionality into BaseInterface
- after all not all Interfaces will be capable of generating reports. The
original design we discussed (notes from the meeting here:
https://github.com/poldracklab/fmriprep/issues/176) involved a mixin class
instead of modification of BaseInterface. This solution seems better and
can still be incorporated into nipype.

I currently don't see advantages of refactoring the code to use run()
(especially considering other burning issues), but we can discuss further
tomorrow.

**Comment by shoshber** [comment]
Ah, there has been a miscommunication. I thought the mixin was a temporary
solution for niworkflows, but that it would be merged into nipype as a
superclass or into BaseInterface. The reason is that nipype has no multiple
inheritance at all, which I assumed is by policy. Unfortunately Report
Input/Output Spec classes cannot be implemented as mixins because they must
inherit from TraitSpec (@oesteban). There are some principled reasons to
avoid multiple inheritances:
https://en.wikipedia.org/wiki/Multiple_inheritance#The_diamond_problem. python
does have a neat way to solve this, which we are taking advantage of in
niworkflows, but it's not standard to programming, and seeing as lots of
contributers to nipype are not native pythonistas (or even programmers), it
seems like a good idea to avoid tricky pitfalls. If we think nipype's dev
community won't care about the mixin/multiple inheritance, then we can
leave ReportCapableInterface alone.

@rwblair since you were in this conversation, how did you interpret things?

(I just thought of a third option, which would be creating decorators to
achieve the composition of BaseInterface and ReportCapableInterface.)

**Comment by chrisfilo** [comment]
It seems that report capable input/output specs *are* currently implemented as mixins - see: https://github.com/poldracklab/niworkflows/blob/master/niworkflows/interfaces/registration.py#L12. I gather that this solution can and does work (if it doesn't we will discover it soon).

The general discussion on what is easier for the nipype community is very valuable, but I feel it should take place when this functionality will be proposed for integration as PR to nipy/nipype. I would prefer to avoid costly preemptive refactoring efforts and submit that PR with the current solution and solicit comments.
