### ISSUE TITLE
Add multilabel masks to SignalExtraction 

### ISSUE THREAD

**Issue by wiheto** [poldracklab/niworkflows#301]
At the moment SignalExtraction only take a a list of masks at the same size as the input image. The enhancement would be to allow the label_files to be multi-label (i.e different integers for each ROI/parcel) and also check if the label_files needs to be resized prior to signal extraction. 

Will submit PR soon.

**Comment by oesteban** [comment]
Closed via 038d61fbc86ed7031a586175ebd32e48b5f7b8de
