### ISSUE TITLE
init_brain_extraction_wf vs antsBrainExtraction

### ISSUE THREAD

**Issue by NPann** [poldracklab/niworkflows#327]
Hi, 

What the rationale for making a nipype version of antsBrainExtraction? Just curious about your insights as I am designing a workflow based on ANTs and came across your implementation of init_brain_extraction_wf.

Thanks!

**Comment by effigies** [comment]
antsBrainExtraction is only parallelized to the extent that ANTs developers considered that when writing the script. By moving to a nipype representation, we can parallelize up to the resource limits of the computation environment, constrained by data dependencies (i.e., if step B requires an output of step A, then B will wait on A, but if there is no dependency, parallel execution is permitted).

**Comment by oesteban** [comment]
It also allowed us to generalize the script better. eg. we are running it on rat brains but skipping the use of laplacians as part of the metric as there is not a convoluted gray matter sheet to be aligned.

**Comment by NPann** [comment]
Thanks a lot! Making sense.
