### ISSUE TITLE
(low priority) `_run_interface()` potential issues

### ISSUE THREAD

**Issue by shoshber** [poldracklab/niworkflows#35]
This is regarding this version: https://github.com/poldracklab/niworkflows/blob/7b76941c4ddb243273f8447fcbadd0b1b9ce2c6f/niworkflows/common/report.py#L36

If an exception is raised between lines 48-61, the entire interface will error out, causing the nipype engine to think the node was not successfully run, and potentially halt the entire workflow. This is not ideal behavior. We would probably prefer to catch an error, print a warning, and output an error report. Looking forward to comments.

**Comment by oesteban** [comment]
Since this hasn't bitten at us for over a year I'll assume it is not an issue to worry about. We can always reopen if suddenly pops up.
