### ISSUE TITLE
TST: Calculate coverage

### ISSUE THREAD

**Issue by oesteban** [poldracklab/niworkflows#370]

**Comment by effigies** [comment]
This should be pretty simple by adding `pytest-cov` to the `tests` extra, and codecov to CircleCI to upload. Probably a little jiggering in `codecov.yml` to fix the paths, but plenty of examples in the nipy projects.

**Comment by effigies** [comment]
Looks like we do?

https://codecov.io/gh/poldracklab/niworkflows

**Comment by oesteban** [comment]
Ups

**Comment by effigies** [comment]
Not sure why it doesn't get commented to PRs, though.

**Comment by oesteban** [comment]
I believe it should https://docs.codecov.io/docs/pull-request-comments

**Comment by effigies** [comment]
Agreed.

**Comment by effigies** [comment]
Pretty sure the reason it's failing is because CircleCI is running under our users, not poldracklab. Commits to master succeed, and outside contributions as well.
