### ISSUE TITLE
MAINT: Installation using ``setup.cfg``

### ISSUE THREAD

**Issue by oesteban** [poldracklab/niworkflows#373]

**Comment by jdkent** [comment]
Is there something I can read to learn why `setup.cfg` is preferred for specifying installation instructions over `setup.py`? Or is it a general principle to like configuration files over python/code files?

**Comment by effigies** [comment]
Mostly the latter. I don't know of anything already written, but to sketch out the reasons:

1) For the sake of not repeating yourself, it's nice to have stuff in a single place. This led to a lot of things like `__about__.py` and `info.py` and `version.py`, which would define these things inside the project, and then be evaluated in `setup.py` with something like `eval(open('<project>/info.py', 'r').read())`. In practice, though, you do need to repeat yourself for a few things, unless you want to exert a major effort to build helper scripts that correctly propagate these things (and documentation to onboard new maintainers...). Also, you don't need most of the stuff inside your project, making it all weird, hacky and probably unnecessary.

2) `setup.py` is ridiculously configurable, as it can run literally any Python code. This has resulted in some pretty unmaintainable installation scripts, so reducing the dynamic parts that you can't avoid evaluating to a minimum and putting the rest in a static file is appealing. That `setuptools` has settled on a preferred format gives high confidence that it will continue working for a while.

3) There's also a chicken/egg problem when dependencies need to be installed. Some of this is addressed in (1), by `eval`ing a file that has no dependencies, but it goes a bit deeper in terms of "What if I want to use an alternative build system to `setuptools` and you don't have it installed?" See [PEP 518](https://www.python.org/dev/peps/pep-0518/) for more on this.

4) If we move to a common convention, such as that proposed in `setuptools` and PEP 517, this increases the legibility of our build system to new contributors or just us later on. Even if nobody else hops on this bandwagon, we have about 6-10 projects now that we maintain, and at least keeping them consistent will help reduce our cognitive load.

I have been thinking recently that it would be very nice to have a best practices guide for things like this, and especially for how and when to transition to new systems as the old ones fade away without causing disruption, similar to how the Python language itself has end-of-life schedules for each minor version.
