### ISSUE TITLE
Improvements when using N4BiasFieldCorrection

### ISSUE THREAD

**Issue by oesteban** [poldracklab/niworkflows#388]
As a result of a thorough bug report from @Shotgunosine, in ANTsX/ANTs#822 several recommendations we should adopt for fMRIPrep are given:

  - Rescale the input if negative values are found (https://github.com/ANTsX/ANTs/issues/822#issuecomment-525351111)
  - Sample more voxels (i.e., shrink factor of 2 or 1) - https://github.com/ANTsX/ANTs/issues/822#issuecomment-525364416

**Comment by effigies** [comment]
From my understanding, we don't need to rescale, we just need to threshold the outputs of registration to >= 0.

**Comment by Shotgunosine** [comment]
Thresholding actually didn't fully address the issues. Rescaling did work
on that one test case though. I'm debugging another issue that may be
related to this one and will try to get more information shortly.

**Comment by oesteban** [comment]
Thresholding changes the distribution and the step it creates is exaggerated by the initial log transform of N4. It makes sense that rescaling works better.

**Comment by effigies** [comment]
If the issue is interpolation-induced negative values, then it's not clear that preserving that particular aspect of the distribution is worthwhile, as it's already an artifact. Rescaling while preserving these artifacts could shift the background noise up significantly.

**Comment by oesteban** [comment]
It is undesired and it doesn't make sense as MRI signal, but not an artifact. BSpline interpolation can do this to ensure continuity of the distribution, which is necessary for N4 to find the bias field, which will become an additive offset after log transform.

Finding truncated values breaks the continuity constraints of the BSplines modeling the bias field.

**Comment by Shotgunosine** [comment]
As I'm trying to track my other masking bug down with this data, I've found that the output of split_opt_comb appears to already be partially brain masked. Is that correct behavior? If it is supposed to be masked, is that discontinuity going to disrupt the N4 normalization that happens when masking the bold after transformation to standard space?

**Comment by effigies** [comment]
Okay. So what if we transform the uniformized image, rather than uniformize the transformed image?

**Comment by effigies** [comment]
But @Shotgunosine, I think the issue here was specifically with blip-up/blip-down, which are registered to each other and then N4-corrected? Or was it the EPI masking in template space?

**Comment by Shotgunosine** [comment]
Yeah, that was where the N4 issue was occurring for this particular failure. I'm trying to track down other masking/registrations issues with other scans from this same dataset and I'm suspicious that those other issues may also be related to this same N4 issue. I can move questions about debugging that out to another thread till I've confirmed those suspicions though.
