### ISSUE TITLE
niflow-nipype1-workflows is now a dependency

### ISSUE THREAD

**Issue by oesteban** [poldracklab/niworkflows#410]
After nipy/nipype#3067 was merged, we need to list ``niflow-nipype1-workflows`` as a dependency. Is that correct, @effigies ?

**Comment by oesteban** [comment]
Should this issue be upstreamed to nipype?

**Comment by effigies** [comment]
Why? Do we use one of its workflows?

And we can depend on it, but because it depends on nipype, nipype cannot depend on it.

**Comment by mgxd** [comment]
yeah, this is leading to issues with the build.

https://circleci.com/gh/poldracklab/fmriprep/9929?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by effigies** [comment]
Ah, that looks like sdcflows needs to update its dependencies.

**Comment by oesteban** [comment]
We just need to make sure we pin sdcflows >=0.1.3 wherever needed
