### ISSUE TITLE
Add report capable version of ants.BrainExtraction

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/niworkflows#47]
For reference here's how we use this interface in fmriprep: https://github.com/poldracklab/fmriprep/blob/master/fmriprep/workflows/anatomical.py#L293

**Comment by shoshber** [comment]
The ANTS BrainExtraction interface in nipype has _the same bug_ as the FSL FAST interface did. :(

**Comment by chrisfilo** [comment]
To be honest this was never reported or fixed, because it's almost always used in a Node. This output collection but seems to be only relevant when the Interfaces is used directly.

**Comment by shoshber** [comment]
Actually it was a different problem, I was leaping to conclusions

**Comment by oesteban** [comment]
#49
