### ISSUE TITLE
ANTSRegistrationRPT does not save reports in CircleCI

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/niworkflows#54]

**Comment by shoshber** [comment]
I haven't finished the PR--closing.

**Comment by chrisfilo** [comment]
Isn't your PR implementing ants.BrainExtraction? This issue was about ants.Registration which is already implemented.

**Comment by shoshber** [comment]
http://vignette2.wikia.nocookie.net/simpsons/images/c/c3/D'oh.jpg/revision/latest?cb=20141226214635
