### ISSUE TITLE
Use robust brighness levels when plotting

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/niworkflows#62]
![image](https://cloud.githubusercontent.com/assets/238759/20853676/56e4d664-b8a2-11e6-9587-340dbe96321d.png)

using percentiles - like here: https://github.com/poldracklab/mriqc/blob/813dcdf00a662f34780368fb6e6d0bdc64257973/mriqc/interfaces/viz_utils.py#L170

**Comment by oesteban** [comment]
Another example in niworflows itself (for registration plots):
https://github.com/poldracklab/niworkflows/blob/master/niworkflows/viz/utils.py#L194
