### ISSUE TITLE
Plot WM/GM boundary when FLIRT is running with BBR option

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/niworkflows#74]
Boundary should be plotted as an outline on both moving and fixed images.

**Comment by chrisfilo** [comment]
Background reading: http://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FLIRT_BBR

**Comment by oesteban** [comment]
This would take checking ```isdefined(self.inputs.wm_seg)``` of the FLIRT interface, and then use nilearn ```add_contour``` using the ```self.inputs.wm_seg``` file.
