### ISSUE TITLE
Consider switching the template to LAS

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/niworkflows#76]
FSL and SPM use LAS (X-, Y, Z) instead of RAS (X, Y, Z). We should consider converting the template shipping with niworkflows to this for compatibility reasons. This change will influence mriqc and fmriprep since nb.as_closest_canonical conforms to RAS not LAS. We can use fslreorient2std to achieve this (https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/Orientation%20Explained).

**Comment by chrisfilo** [comment]
However, the original nifti file of the 2009c template is in RAS which would speak towards leaving things as they are. @oesteban @poldrack what do you think?

**Comment by poldrack** [comment]
I *really* don't like changing templates so I would need a really strong argument in favor in order to convince me

**Comment by chrisfilo** [comment]
ITK/ANTs also seem to be in favour of RAS. Let's keep it as it is.

**Comment by oesteban** [comment]
In a long future we can provide also optional LAS artifacts, for compatibility with other software tools. This decision is possibly more involved in diffusion, for the interaction with the b-vectors. I would bet for RAS there as well.
